language: node_js
os: windows

node_js:
  - 6.0.0
  
install:
  - npm install -g codecov
  
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
